<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Subcategory</name>
   <tag></tag>
   <elementGuidId>4294f505-826a-4471-af35-db572fbe696e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href='/category_products/1']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='${category}']//a[normalize-space(.)='${subcategory}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dress</value>
      <webElementGuid>83d9e209-da95-41b8-99a0-80a4fd50fed7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
