<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Category</name>
   <tag></tag>
   <elementGuidId>1d7a84a1-122f-4451-9f65-7d369530511d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id='${category}']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href='#${category}' or normalize-space(.)='${category}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Women</value>
      <webElementGuid>9c50ff6e-d0c9-4a94-850a-f3c103f122d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Women</value>
      <webElementGuid>cc1ddd76-61de-435f-bd56-d2262b25b175</webElementGuid>
   </webElementProperties>
</WebElementEntity>
